# docker-compose.yml
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data # persist games & model
    working_dir: /app
    environment:
      - AUTO_TRAIN=1 # set 0 to disable auto fine-tune
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:delegated # live code
      - /app/node_modules # ← container-managed deps (prevents host overwrite)
    working_dir: /app
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
